#+TITLE: JoaoESmoreira
#+AUTHOR: Joao ES Moreira
#+SETUPFILE: ~/Documents/OrgFiles/themes/responsive-dark-light.setup
#+INCLUDE: "./header.org"

* About
Joaoesmoreia.com is a site created by Joao ES Moreira.

I hold both a Master's and a Bachelor's degree in Informatics
Engineering from the Department of Informatics Engineering at the
University of Coimbra, where I specialized in Intelligent Systems. My
master’s thesis focused on posted-price search in multimodal
transport networks.

Throughout my academic journey, I have taken opportunities to improve
my problem-solving and algorithmic thinking skills. I successfully
completed the non-degree courses "Competitive Programming I" and
"Competitive Programming II," which deepened my understanding of
problem modeling, heuristics, and meta-heuristics. As part of this
training, I participated in the [[https://www.uc.pt/fctuc/dei/noticias/miup-2023/][Portuguese Inter-University
Programming Marathon (MIUP 2023)]] and the [[https://swerc.eu/2023/][Southwestern Europe Regional
Contest (SWERC 2023)]].

I have developed strong proficiency in multiple programming languages,
including Python, C, C++, Java, and MATLAB. 

During my time at the Centre for Informatics and Systems of the
University of Coimbra ([[https://www.cisuc.uc.pt/en][CISUC]]), I worked as a researcher focusing on
intelligent decision-making and optimization in multimodal transport
networks. I actively contributed to the [[https://roar-net.eu/][Randomised Optimisation
Algorithms Research Network (ROAR-net)]], where I participated in the
[[https://roar-net.eu/events/first-training-school/][First ROAR-NET Training School]] in Luxembourg Institute of Science and
Technology (LIST), and in the [[https://roar-net.eu/events/code-fest/][ROAR-NET Problem Modelling Code Fest]].  I
also participated in the [[https://www.multicriterio.es/IMCDM-MCDA25.html][1st IBERIAN CONFERENCE ON MCDM/A (IMCDM/A)]],
where I exchanged ideas with leading experts in the field of
decision support and multi-criteria analysis.

Additionally, I gained practical web development experience through my
involvement with the Academic Group of Informatics Students, where I
contributed to the creation of websites for departmental events. This
experience allowed me to enhance my skills in JavaScript and the React
framework.

* Contacts
- *Personal email*: jesmoreira2010@gmail.com
- *institutional email*: joaomoreira@student.dei.uc.pt

- *GitHub*: https://github.com/JoaoESmoreira
- *Linkdin*: https://www.linkedin.com/in/jo%C3%A3o-moreira-1a4573235/

* Footer
#+INCLUDE: "./footer.org"
