
#+TITLE: JoaoESmoreira
#+AUTHOR: Joao ES Moreira
#+SETUPFILE: ~/Documents/OrgFiles/themes/responsive-dark-light.setup
#+INCLUDE: "./header.org"

* Mu4e

Hello there!

In this blog I will show you how I configured my email accounts on
Emacs and a simple use case, using *mu4e*. Of course, you can find the
complete source code of my emacs configuration on my GitHub repository
[[https://github.com/JoaoESmoreira/emacsphere/]] . There is also a
dedicated tab for the project at [[file:./emacsphere.org][Emacsphere]].

** Requirements

Let's start by installing all required packages. In my case, I am
installing it on *Arch Linux* by the way.

#+begin_src emacs-lisp
sudo pacman -S isync msmtp 
yay -S mu
#+end_src

** Configuring Mbsync

*** Encripting Passwords
First thing first, let’s securely store and encrypt your passwords.

#+begin_src emacs-lisp
mkdir -p .password-store/
cd .passwrod-store

touch "your-password" > gmail
touch "your-password" > dei

gpg -c .password-store/gmail
gpg -c .password-store/dei

rm gmail dei
#+end_src

If you’re using Gmail, you must create an App Password.  You can do
this by visiting: https://myaccount.google.com/apppasswords

*** Setting up mbsyncrc
Create the configuration file at =~/.mbsyncrc= and past the following
content. Make sure you replace email addresses with your actual ones.

#+begin_src emacs-lisp
# #############
# # gmail
# #############
IMAPAccount gmail
Host imap.gmail.com
User your-email-address@gmail.com
PassCmd "gpg --no-tty --for-your-eyes-only -dq ~/.password-store/gmail.gpg"
TLSType IMAPS

IMAPStore gmail-remote
Account gmail

MaildirStore gmail-local
Path ~/Mail/gmail/
Inbox ~/Mail/gmail/INBOX

Channel gmail
Far :gmail-remote:
Near :gmail-local:
Patterns *
Create Both
Expunge Both
SyncState *

#############
# DEI
#############
IMAPAccount dei
Host student.dei.uc.pt
User your-email-address
PassCmd "gpg --no-tty --for-your-eyes-only -dq ~/.password-store/dei.gpg"
TLSType IMAPS
Port 993

IMAPStore dei-remote
Account dei

MaildirStore dei-local
Path ~/Mail/dei/
Inbox ~/Mail/dei/INBOX
Subfolders Verbatim

Channel dei
Far :dei-remote:
Near :dei-local:
Patterns INBOX mail/Drafts mail/Junk mail/sent-mail mail/Trash
Create Both
Expunge Both
SyncState *
#+end_src

Before syncing your emails, make sure to create the local mail
directories:

#+begin_src emacs-lisp
mkdir -p ~/Mail/gmail
mkdir -p ~/Mail/dei
#+end_src

** Setting up MU and Indexing

Now, sync your emails and index them using *mu*.

#+begin_src emacs-lisp
mbsync -a
mu init --maildir=~/Mail --my-address=your_address@gmail.com --my-address=your_address@student.dei.uc.pt
mu index                                                                                                 
#+end_src

** Configuring mu4e in Emacs
Paste the following configuration in your Emacs config file:

#+begin_src emacs-lisp
(use-package mu4e
  :ensure nil
  :load-path "/usr/share/emacs/site-lisp/mu4e/"
  :config
  (setq mu4e-change-filenames-when-moving t
        mu4e-update-interval (* 3 60)
        mu4e-get-mail-command "mbsync -a"
        mu4e-maildir "~/Mail"
        message-send-mail-function 'smtpmail-send-it
        auth-sources '("~/.authinfo.gpg"))

  ;; sort emails by date
  (setq mu4e-headers-sort-field :date)
  (setq mu4e-headers-sort-direction 'descending)

  ;; Shortcuts
  (setq mu4e-maildir-shortcuts
        '(("/gmail/INBOX"             . ?g)
          ("/gmail/Sent"              . ?G)
          ("/gmail/Trash"             . ?x)
          ("/gmail/Drafts"            . ?d)
          ("/dei/INBOX"               . ?i)
          ("/dei/mail/sent-mail"      . ?s)
          ("/dei/mail/Trash"          . ?t)
          ("/dei/mail/Drafts"         . ?D)))

  ;; Context for multiple accounts
  (setq mu4e-contexts
        `( ,(make-mu4e-context
             :name "Gmail"
             :enter-func (lambda () (mu4e-message "Loading Gmail..."))
             :match-func (lambda (msg)
                           (when msg
                             (string-prefix-p "/gmail" (mu4e-message-field msg :maildir))))
             :vars '((user-mail-address . "your-address@gmail.com")
                     (user-full-name . "username1")
                     (mu4e-sent-folder   . "/gmail/Sent")
                     (mu4e-drafts-folder . "/gmail/Drafts")
                     (mu4e-trash-folder  . "/gmail/Trash")
                     (mu4e-refile-folder . "/gmail/Archive")
                     (smtpmail-smtp-server . "smtp.gmail.com")
                     (smtpmail-smtp-service . 465)
                     (smtpmail-stream-type . ssl)))

           ,(make-mu4e-context
             :name "DEI"
             :enter-func (lambda () (mu4e-message "Loading DEI..."))
             :match-func (lambda (msg)
                           (when msg
                             (string-prefix-p "/dei" (mu4e-message-field msg :maildir))))
             :vars '((user-mail-address . "your-address@student.dei.uc.pt")
                     (user-full-name . "username2")
                     (mu4e-sent-folder   . "/dei/mail/sent-mail")
                     (mu4e-drafts-folder . "/dei/mail/Drafts")
                     (mu4e-trash-folder  . "/dei/mail/Trash")
                     (mu4e-refile-folder . "/dei/mail/Archive")
                     (smtpmail-smtp-server . "smtp.dei.uc.pt")
                     (smtpmail-smtp-service . 465)
                     (smtpmail-stream-type . ssl)))))
)
#+end_src
** Configuring msmtp
*Msmtp* is a simple and effective SMTP client we use to send emails
from Emacs through *mu4e*.

*** Create the configuration file

Create a file called =~/.msmtprc= with the following content. Replace
all placeholder values with your actual information:

#+begin_src conf :tangle ~/.msmtprc
# Set default values
defaults
auth           on
tls            on
tls_trust_file /etc/ssl/certs/ca-certificates.crt
logfile        ~/.msmtp.log

# Gmail account
account gmail
host smtp.gmail.com
port 465
from your-address@gmail.com
user your-address@gmail.com
passwordeval gpg --no-tty --for-your-eyes-only -dq ~/.password-store/gmail.gpg
tls_starttls off
tls on

# DEI account
account dei
host smtp.dei.uc.pt
port 465
from your-address@student.dei.uc.pt
user your-address@student.dei.uc.pt
passwordeval gpg --no-tty --for-your-eyes-only -dq ~/.password-store/dei.gpg
tls_starttls off
tls on

# Set default account
account default : gmail
#+end_src

*** Secure the file

*Msmtp* expects the configuration file to be *only readable by the
user* for security reasons. So, change the permissions:

#+begin_src emacs-lisp
chmod 600 ~/.msmtprc
#+end_src

* Using Mu4e - Use Case

Once everything is configured, you are ready to start managing your
emails directly from Emacs using *Mu4e*.

** Launch Mu4e

Open Emacs and launch Mu4e by typing:

#+begin_src emacs-lisp
M-x mu4e
#+end_src

This will open the *mu4e* main dashboard.

** Interface Overview

*Mu4e* is divided into sections:

- *Jump to maildir*: Quickly go to a mailbox (e.g., inbox, sent).
- *Compose a new message*: Start writing a new email.
- *Update mail & index*: Syncs emails using *mbsync* and re-indexes them with *mu*.
- *Search mail*: Allows you to perform complex searches.
- *Bookmarks*: Custom queries for quick access.

** Basic Shortcuts

Here is a table with essential *mu4e* commands and keybindings:

| Action                   | Keybinding |
|--------------------------+------------|
| Open Mu4e                | M-x mu4e   |
| Sync & index mail        | U          |
| Compose a new email      | C          |
| Reply to a message       | R          |
| Forward a message        | f          |
| Mark for deletion        | d          |
| Move to another folder   | m          |
| Search mails             | /          |
| View attachment          | V          |
| Toggle context (account) | ;          |
| Send                     | C-c C-c    |

** Writing and Sending Emails

To compose a new email:

1. Press =c= inside *mu4e*.
2. Fill in the =To:=, =Subject:= and message body.
3. Press =C-c C-c= to send.

*Mu4e* will send your message using *msmtp* based on the current
context (Gmail or DEI).

** Switching Contexts

If you configured *mu4e-contexts*, *mu4e* automatically chooses the
context based on the folder or message. But you can also manually
switch:

#+begin_src emacs-lisp
; Switch context manually
M-x mu4e-context-switch
#+end_src

You can also press =;= while inside *mu4e* to switch between configured contexts.

** Searching Emails

You can search all indexed mail using =/=:

#+begin_example
from:someone@example.com subject:meeting date:today
#+end_example

You can use advanced queries like:

- *flag:unread* – Unread emails
- *maildir:/gmail/INBOX* – Mails in Gmail inbox
- *to:joao* – Emails sent to João

** Syncing Mail

To manually sync your mail (run *mbsync* and reindex):

#+begin_src emacs-lisp
U
#+end_src

Alternatively, *mu4e* is configured to sync automatically every 3
minutes based on:

#+begin_src emacs-lisp
(setq mu4e-update-interval (* 3 60)) ; every 3 minutes
#+end_src

** Deleting and Archiving

- Press =d= to mark an email for trash.
- Press =r= to refile (archive) a message.
- Execute marked actions with =x=.


* Final Thoughts

And that's it! You now have a fully working setup of *mu4e* with
multiple email accounts in Emacs. This configuration is both minimal
and powerful, giving you a streamlined workflow integrated right into
your Emacs environment.

If you have any questions or suggestions, feel free to open an issue
or pull request on the GitHub repository.

* Footer
#+INCLUDE: "./footer.org"
